apiVersion: v1
kind: Service
metadata:
  name: svc-db-camellia-test
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '16379'
    prometheus.io/services: 'true'
    prometheus.io/scrape_slow: 'true'
    prometheus.io/path: '/prometheus'

spec:
  ports:
  - name: port-6380
    protocol: TCP
    port: 6380
    targetPort: 6380
  - name: port-16379
    protocol: TCP
    port: 16379
    targetPort: 16379

  selector:
    app: pod-db-camellia-test
