version: '3'
services:
    redis_master1:
        container_name: redis_master1
        image: redis:6.0.5-alpine3.12

    redis_slave1:
        container_name: redis_slave01
        image: redis:6.0.5-alpine3.12
        command: ["redis-server", "--replicaof redis_master1 6379"]

    redis_slave2:
        container_name: redis_slave02
        image: redis:6.0.5-alpine3.12
        command: ["redis-server", "--replicaof redis_master1 6379"]

    camellia_proxy_rw:
        container_name: camellia_proxy_rw
        image: 48n6e/camellia-redis-proxy:1.2.30-jdk-22-0.0.1
        volumes:
            - "./application.yml:/opt/camellia-redis-proxy/BOOT-INF/classes/application.yml"
            - "./resource-table.json:/opt/camellia-redis-proxy/BOOT-INF/classes/resource-table.json"
        command: ["java", "-XX:+UseG1GC","-Dio.netty.tryReflectionSetAccessible=true","--add-opens","java.base/java.lang=ALL-UNNAMED","--add-opens","java.base/java.io=ALL-UNNAMED","--add-opens","java.base/java.math=ALL-UNNAMED","--add-opens","java.base/java.net=ALL-UNNAMED","--add-opens","java.base/java.nio=ALL-UNNAMED","--add-opens","java.base/java.security=ALL-UNNAMED","--add-opens","java.base/java.text=ALL-UNNAMED","--add-opens","java.base/java.time=ALL-UNNAMED","--add-opens","java.base/java.util=ALL-UNNAMED","--add-opens","java.base/jdk.internal.access=ALL-UNNAMED","--add-opens","java.base/jdk.internal.misc=ALL-UNNAMED","--add-opens","java.base/sun.net.util=ALL-UNNAMED","-XX:+UseContainerSupport", "-Xms128m","-Xmx4096m","-server","org.springframework.boot.loader.JarLauncher"]
